FROM nginx:alpine
COPY index-template.html /tmp/
RUN apk add --no-cache envsubst
ENV TITLE="Default Title"
ENV HEADING="Default Heading"  
ENV ENV="development"
CMD envsubst < /tmp/index-template.html > /usr/share/nginx/html/index.html && nginx -g 'daemon off;'
